SELECT *
FROM BANK_TRANSACTIONS
WHERE (:#AMOUNT IS NULL OR AMOUNT >= :#AMOUNT)
  AND (:#CURRENCY IS NULL OR CURRENCY = :#CURRENCY)
  AND (:#TRANSACTION_TYPE IS NULL OR TRANSACTION_TYPE = :#TRANSACTION_TYPE)
  AND (:#STATUS IS NULL OR STATUS = :#STATUS)
  AND (:#BRANCH_CODE IS NULL OR BRANCH_CODE = :#BRANCH_CODE)
ORDER BY TRANSACTION_ID
